apiVersion: v1
kind: Service
metadata:
  labels:
    app: otus-hw10-saga-app
  name: otus-hw10-saga-stock-service
spec:
  selector:
    app: otus-hw10-saga-app
  ports:
    - protocol: TCP
      port: 9002
      targetPort: web-stock
      name: web-stock
  type: NodePort