apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otus-hw6-cache-app
  name: otus-hw6-cache-deployment
spec:
    replicas: 1
    selector:
       matchLabels:
          app: otus-hw6-cache-app
    template:
       metadata:
          labels:
             app: otus-hw6-cache-app
       spec:
          containers:
          - name: otus-hw6-cache
            image: evgen2sat/otus-hw6-cache:1.0.0
            ports:
              - name: web 
                containerPort: 8003
            env:
              - name: JDBC_DRIVER_CLASS_NAME
                valueFrom:
                    secretKeyRef:
                        name: otus-hw6-cache-secret
                        key: JDBC_DRIVER_CLASS_NAME
              - name: JDBC_URL
                valueFrom:
                    secretKeyRef:
                        name: otus-hw6-cache-secret
                        key: JDBC_URL
              - name: JDBC_USER
                valueFrom:
                    secretKeyRef:
                        name: otus-hw6-cache-secret
                        key: JDBC_USER
              - name: JDBC_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: otus-hw6-cache-secret
                        key: JDBC_PASSWORD
              - name: CACHE_ENABLED
                value: "0"
              - name: REDIS_HOST
                value: "redis-master"
              - name: REDIS_PORT
                value: "6379"
            livenessProbe:
              httpGet:
                port: 8003
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 8003
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5