apiVersion: v1
kind: Secret
metadata:
  name: otus-hw10-saga-order-secret
type: Opaque
data:
  JDBC_DRIVER_CLASS_NAME: b3JnLnBvc3RncmVzcWwuRHJpdmVy
  JDBC_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9teWFwcA==
  JDBC_USER: bXl1c2Vy
  JDBC_PASSWORD: cGFzc3dk
  DATABASE_URI: InBvc3RncmVzcWw6Ly9teXVzZXI6cGFzc3dkQHBvc3RncmVzOjU0MzIvbXlhcHAi