micronaut:
  application:
    name: hw5-api-gateway
  server:
    port: 8000
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false