micronaut:
  application:
    name: hw5-api-gateway-auth
  server:
    port: 9001
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: eXJneEw2VDBteWtPRlBIcmxaUk1Zc3E1UjBHQzFRY2FYOTlIcTVMNWd0RjVoVm5FVTcyWUJ0ZXpvczhBY1p4ZXkyNkZVWmNUeUNCeDFFRGI2T0d0QkRvUkRuUUlUNno5RkI2aw==
              base64: true
              jws-algorithm: HS512