{
 "title": "otus-hw4-prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS BY INGRESS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "RPS BY ENDPOINTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "ERROR RATE BY INGRESS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)\r\n(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "ERROR RATE BY ENDPOINTS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "LATENCY BY ENDPOINTS (0.5, 0.95, 0.99. +Inf)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\nsum by (le, exported_endpoint)\r\n(rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95,\r\nsum by (le, exported_endpoint)\r\n(rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99,\r\nsum by (le, exported_endpoint)\r\n(rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(+Inf,\r\nsum by (le, exported_endpoint)\r\n(rate(app_request_latency_seconds_bucket[1m]))\r\n) * 1000"
    }
   ]
  },
  {
   "title": "LATENCY BY INGRESS (0.5, 0.95, 0.99, +Inf)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\nsum by (le)\r\n(rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95,\r\nsum by (le)\r\n(rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99,\r\nsum by (le)\r\n(rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))\r\n) * 1000"
    },
    {
     "expr": "histogram_quantile(+Inf,\r\nsum by (le)\r\n(rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))\r\n) * 1000"
    }
   ]
  }
 ]
}