apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otus-hw4-prometheus-app
  name: otus-hw4-prometheus-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: otus-hw4-prometheus-app
    template:
       metadata:
          labels:
             app: otus-hw4-prometheus-app
       spec:
          containers:
          - name: otus-hw4-prometheus
            image: evgen2sat/otus-hw4-prometheus:1.0.1
            ports:
              - name: web 
                containerPort: 8000
            env:
              - name: JDBC_DRIVER_CLASS_NAME
                valueFrom:
                    secretKeyRef:
                        name: otus-hw4-prometheus-secret
                        key: JDBC_DRIVER_CLASS_NAME
              - name: JDBC_URL
                valueFrom:
                    secretKeyRef:
                        name: otus-hw4-prometheus-secret
                        key: JDBC_URL
              - name: JDBC_USER
                valueFrom:
                    secretKeyRef:
                        name: otus-hw4-prometheus-secret
                        key: JDBC_USER
              - name: JDBC_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: otus-hw4-prometheus-secret
                        key: JDBC_PASSWORD
            livenessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5