apiVersion: batch/v1
kind: Job
metadata:
  name: otus-hw4-prometheus-initdb
spec:
  template:
    metadata:
      name: otus-hw4-prometheus-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: "postgresql://myuser:passwd@postgres:5432/myapp"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              create table users (id bigserial not null constraint users_pk primary key,
                    last_name   text                    not null,
                    first_name     text                    not null,
                    middle_name text                    null,
                    created_date  timestamp default now() not null,
                    deleted boolean default false not null
                );
            EOF
  backoffLimit: 0