apiVersion: v1
kind: Service
metadata:
  name: otus-hw3-postgres-service
spec:
  selector:
    app: otus-hw3-postgres-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web 
  type: NodePort