apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otus-hw11-sharding-app
  name: otus-hw11-sharding-deployment
spec:
    replicas: 1
    selector:
       matchLabels:
          app: otus-hw11-sharding-app
    template:
       metadata:
          labels:
             app: otus-hw11-sharding-app
       spec:
          containers:
          - name: otus-hw6-cache
            image: evgen2sat/otus-hw11-sharding:1.0.4
            ports:
              - name: web 
                containerPort: 8003
            env:
              - name: JDBC_DRIVER_CLASS_NAME
                valueFrom:
                    secretKeyRef:
                        name: otus-hw11-sharding-secret
                        key: JDBC_DRIVER_CLASS_NAME
              - name: JDBC_URL
                valueFrom:
                    secretKeyRef:
                        name: otus-hw11-sharding-secret
                        key: JDBC_URL
              - name: JDBC_USER
                valueFrom:
                    secretKeyRef:
                        name: otus-hw11-sharding-secret
                        key: JDBC_USER
              - name: JDBC_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: otus-hw11-sharding-secret
                        key: JDBC_PASSWORD
            livenessProbe:
              httpGet:
                port: 8003
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 8003
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5