apiVersion: batch/v1
kind: Job
metadata:
  name: otus-hw11-sharding-initdb-category-1
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      name: otus-hw11-sharding-initdb-category-1
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: "postgresql://myuser:passwd@products-1:6432/products-1"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              create table products (id bigserial not null constraint products_pk primary key,
                    name   text                    not null,
                    color     text                    not null,
                    price float                    not null,
                    category_id bigint                    not null CONSTRAINT category_id_check CHECK (category_id = 1),
                    created_date  timestamp default now() not null,
                    deleted boolean default false not null
                );
            EOF
  backoffLimit: 5