---
apiVersion: v1
kind: Service
metadata:
  name: postgres-1
  labels:
    app: postgres-1
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres-1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset-1
spec:
  serviceName: "postgres-1"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-1
  template:
    metadata:
      labels:
        app: postgres-1
    spec:
      containers:
      - name: postgres-1
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgredb-1
        env:
          - name: POSTGRES_DB
            value: products-1
          - name: POSTGRES_USER
            value: myuser
          - name: POSTGRES_PASSWORD
            value: passwd
        volumeMounts:
        - name: postgredb-1
          mountPath: /var/lib/postgresql/data
          subPath: postgres-1
  volumeClaimTemplates:
  - metadata:
      name: postgredb-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi